connectiondialog: switch to QThread::msleep() to support Qt < 6.6
'void QThread::sleep(std::chrono::nanoseconds nsecs)' was introduced in Qt 6.6:
https://doc.qt.io/qt-6/qthread.html#sleep

To support older Qts, we need to use the older msleep.

This addresses the following CI failure:

/home/runner/work/incolata/incolata/connectiondialog.cpp: In member function ‘virtual void PortLoaderThread::run()’:
/home/runner/work/incolata/incolata/connectiondialog.cpp:152:24: error: cannot convert ‘std::chrono::milliseconds’ {aka ‘std::chrono::duration<long int, std::ratio<1, 1000> >’} to ‘long unsigned int’
  152 |     sleep(std::chrono::milliseconds{ 1000 });
      |                        ^~~~~~~~~~~~~~~~~~~~
      |                        |
      |                        std::chrono::milliseconds {aka std::chrono::duration<long int, std::ratio<1, 1000> >}
In file included from /home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtCore/QThread:1,
                 from /home/runner/work/incolata/incolata/connectiondialog.h:8,
                 from /home/runner/work/incolata/incolata/connectiondialog.cpp:1:
/home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtCore/qthread.h:128:23: note:   initializing argument 1 of ‘static void QThread::sleep(long unsigned int)’
  128 |     static void sleep(unsigned long);
      |                       ^~~~~~~~~~~~~

Originally introduced in:
https://github.com/ahunt/incolata/commit/036d90f8075bc6e0a9663883f46ae5f5bb7a11c9