connectiondialog: declare default equality operator instead of spaceship (to fix Mac build)
Clang on OSX doesn't like the spaceship, and we only need equality anyway:

> [16/27] Building CXX object CMakeFiles/incolata.dir/incolata_autogen/mocs_compilation.cpp.o
> FAILED: CMakeFiles/incolata.dir/incolata_autogen/mocs_compilation.cpp.o
> /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DQT_CHARTS_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -I/Users/runner/work/incolata/incolata/build/incolata_autogen/include -I/Users/runner/work/incolata/incolata/build/include -I/Users/runner/work/incolata/incolata -isystem /opt/homebrew/lib/QtCore.framework/Headers -iframework /opt/homebrew/lib -isystem /opt/homebrew/share/qt/mkspecs/macx-clang -isystem /opt/homebrew/include -isystem /opt/homebrew/lib/QtWidgets.framework/Headers -isystem /opt/homebrew/lib/QtGui.framework/Headers -isystem /opt/homebrew/lib/QtCharts.framework/Headers -isystem /opt/homebrew/lib/QtOpenGL.framework/Headers -isystem /opt/homebrew/lib/QtOpenGLWidgets.framework/Headers -O3 -DNDEBUG -std=gnu++17 -arch arm64 -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -std=c++20 -Wall -Wextra -Wpedantic -Werror -MD -MT CMakeFiles/incolata.dir/incolata_autogen/mocs_compilation.cpp.o -MF CMakeFiles/incolata.dir/incolata_autogen/mocs_compilation.cpp.o.d -o CMakeFiles/incolata.dir/incolata_autogen/mocs_compilation.cpp.o -c /Users/runner/work/incolata/incolata/build/incolata_autogen/mocs_compilation.cpp
> In file included from /Users/runner/work/incolata/incolata/build/incolata_autogen/EWIEGA46WW/moc_connectiondialog.cpp:9:
> /Users/runner/work/incolata/incolata/build/incolata_autogen/EWIEGA46WW/../../../connectiondialog.h:97:8: error: explicitly defaulted three-way comparison operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
>   auto operator<=>(const PortInfo&) const = default;
>        ^
> /Users/runner/work/incolata/incolata/build/incolata_autogen/EWIEGA46WW/../../../connectiondialog.h:94:11: note: defaulted 'operator<=>' is implicitly deleted because there is no viable three-way comparison function for member 'mID'
>   QString mID;
>           ^
> /Users/runner/work/incolata/incolata/build/incolata_autogen/EWIEGA46WW/../../../connectiondialog.h:97:45: note: replace 'default' with 'delete'
>   auto operator<=>(const PortInfo&) const = default;
>                                             ^~~~~~~
>                                             delete
> 1 error generated.