Q_DECLARE_OPAQUE_POINTER/Q_DECLARE_METATYPE(TestConfig*) to fix Qt 6.2 builds
The following failure only occurs in CI (Qt 6.2) but not locally (Qt 6.8):

[15/17] Building CXX object CMakeFiles/incolata.dir/mainwindow.cpp.o
FAILED: CMakeFiles/incolata.dir/mainwindow.cpp.o
/usr/bin/c++ -DQT_CHARTS_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -I/home/runner/work/incolata/incolata/build/incolata_autogen/include -I/home/runner/work/incolata/incolata -isystem /home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtCore -isystem /home/runner/work/incolata/Qt/6.2.4/gcc_64/include -isystem /home/runner/work/incolata/Qt/6.2.4/gcc_64/mkspecs/linux-g++ -isystem /home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtWidgets -isystem /home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtGui -isystem /home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtCharts -isystem /home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtOpenGL -isystem /home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtOpenGLWidgets -std=gnu++17 -Wall -Wextra -Wpedantic -Werror -fPIC -MD -MT CMakeFiles/incolata.dir/mainwindow.cpp.o -MF CMakeFiles/incolata.dir/mainwindow.cpp.o.d -o CMakeFiles/incolata.dir/mainwindow.cpp.o -c /home/runner/work/incolata/incolata/mainwindow.cpp
In file included from /home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtCore/qobject.h:54,
                 from /home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtWidgets/qwidget.h:45,
                 from /home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtWidgets/qmainwindow.h:44,
                 from /home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtWidgets/QMainWindow:1,
                 from /home/runner/work/incolata/incolata/mainwindow.h:4,
                 from /home/runner/work/incolata/incolata/mainwindow.cpp:1:
/home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtCore/qmetatype.h: In instantiation of ‘struct QtPrivate::IsPointerToTypeDerivedFromQObject<const TestConfig*>’:
/home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtCore/qmetatype.h:1112:60:   required from ‘struct QMetaTypeId<const TestConfig*>’
/home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtCore/qmetatype.h:1132:38:   required from ‘struct QMetaTypeId2<const TestConfig*>’
/home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtCore/qobject_impl.h:68:41:   required from ‘struct QtPrivate::TypesAreDeclaredMetaType<QtPrivate::List<const TestConfig*, void*, void*, const QString&, const QString&, const QString&> >’
/home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtCore/qobject.h:237:86:   required from ‘static QMetaObject::Connection QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const typename QtPrivate::FunctionPointer<Func2>::Object*, Func2, Qt::ConnectionType) [with Func1 = void (MainWindow::*)(const TestConfig*, void*, void*, const QString&, const QString&, const QString&); Func2 = void (TestWorker::*)(const TestConfig*, void*, void*, const QString&, const QString&, const QString&); typename QtPrivate::FunctionPointer<Func>::Object = MainWindow; typename QtPrivate::FunctionPointer<Func2>::Object = TestWorker]’
/home/runner/work/incolata/incolata/mainwindow.cpp:196:10:   required from here
/home/runner/work/incolata/Qt/6.2.4/gcc_64/include/QtCore/qmetatype.h:853:23: error: invalid application of ‘sizeof’ to incomplete type ‘const TestConfig’
  853 |         static_assert(sizeof(T), "Type argument of Q_PROPERTY or Q_DECLARE_METATYPE(T*) must be fully defined");
      |                       ^~~~~~~~~
[16/17] Building CXX object CMakeFiles/incolata.dir/testworker.cpp.o
ninja: build stopped: subcommand failed.